language: bash
sudo: required
services:
  - docker
script:
  - cd grafana && DEV_REGISTRY="docker.io" make test && cd ..
  - cd telegraf && DEV_REGISTRY="docker.io" make test && cd ..
notifications:
  slack:
    rooms:
      - drycc:xKmLlmJR4hfRAgVIOwdpAoC9#drycc
