apiVersion: v1
kind: Service
metadata:
  name: drycc-grafana
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
    app: drycc-grafana
spec:
  ports:
  - port: 80
    name: grafana
    targetPort: grafana
  - port: 9094
    name: alerting
    targetPort: alerting
  selector:
    app: drycc-grafana
