apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drycc-monitor-telegraf
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  selector:
    matchLabels:
      app: drycc-monitor-telegraf
  {{- if ge .Capabilities.KubeVersion.Minor "6" }}
  updateStrategy:
    type: RollingUpdate
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: drycc-monitor-telegraf
    spec:
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      serviceAccount: drycc-monitor-telegraf
      initContainers:
      - name: drycc-monitor-telegraf-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -u
        - $(POSTGRESQL_CONNECTION)
        {{- include "telegraf.envs" . | indent 8 }}
      containers:
      - name: drycc-monitor-telegraf
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/telegraf:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- end }}
        {{- if or (.Values.telegraf.limitsCpu) (.Values.telegraf.limitsMemory)}}
        resources:
          limits:
            {{- if (.Values.telegraf.limitsCpu) }}
            cpu: {{.Values.telegraf.limitsCpu}}
            {{- end}}
            {{- if (.Values.telegraf.limitsMemory) }}
            memory: {{.Values.telegraf.limitsMemory}}
            {{- end}}
        {{- end}}
        {{- include "telegraf.envs" . | indent 8 }}
