{{- if eq .Values.global.grafanaLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-monitor-grafana
  annotations:
    {{- with .Values.grafana.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
    app: drycc-monitor-grafana
spec:
  ports:
  - port: 80
    name: ui
    targetPort: ui
  selector:
    app: drycc-monitor-grafana
{{- end }}
