{{ if .Values.global.certManagerEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drycc-monitor-grafana
spec:
  secretName: drycc-monitor-grafana-auto-tls
  issuerRef:
    name: drycc-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - drycc-monitor-grafana.{{ .Values.global.platformDomain }}
  privateKey:
    rotationPolicy: Always
{{- end }}
