apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-monitor-telegraf
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.telegraf.imageTag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drycc-monitor-telegraf
  {{- if ge .Capabilities.KubeVersion.Minor "6" }}
  updateStrategy:
    type: RollingUpdate
  {{- end }}
  template:
    metadata:
      labels:
        app: drycc-monitor-telegraf
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.telegraf.podAffinityPreset.type "key" .Values.telegraf.podAffinityPreset.key "values" .Values.telegraf.podAffinityPreset.values ) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.telegraf.podAntiAffinityPreset.type "key" .Values.telegraf.podAntiAffinityPreset.key "values" .Values.telegraf.podAntiAffinityPreset.values ) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.telegraf.nodeAffinityPreset.type "key" .Values.telegraf.nodeAffinityPreset.key "values" .Values.telegraf.nodeAffinityPreset.values ) | nindent 10 }}
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      serviceAccount: drycc-monitor-telegraf
      initContainers:
      - name: drycc-monitor-telegraf-init
        image: {{.Values.imageRegistry}}/{{.Values.telegraf.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - netcat
          - -v
          - -u
          - $(INFLUXDB_URLS_V2)
        env:
{{- if eq .Values.global.influxdbLocation "off-cluster" }}
        - name: "INFLUXDB_URLS_V2"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: url
{{- else }}
        - name: "INFLUXDB_URLS_V2"
          value: "\"http://$(DRYCC_INFLUXDB_SERVICE_HOST):$(DRYCC_INFLUXDB_SERVICE_PORT_TRANSPORT)\""
        - name: "INFLUXDB_V2_INPUT_URLS"
          value: "\"http://$(DRYCC_INFLUXDB_SERVICE_HOST):$(DRYCC_INFLUXDB_SERVICE_PORT_TRANSPORT)/metrics\""
        - name: "ENABLE_INFLUXDB_V2_INPUT"
          value: "true"
{{- end }}
      containers:
      - name: drycc-monitor-telegraf
        image: {{.Values.telegraf.imageRegistry}}/{{.Values.telegraf.imageOrg}}/telegraf:{{.Values.telegraf.imageTag}}
        imagePullPolicy: {{.Values.telegraf.imagePullPolicy}}
{{- if or (.Values.telegraf.limitsCpu) (.Values.telegraf.limitsMemory)}}
        resources:
          limits:
{{- if (.Values.telegraf.limitsCpu) }}
            cpu: {{.Values.telegraf.limitsCpu}}
{{- end}}
{{- if (.Values.telegraf.limitsMemory) }}
            memory: {{.Values.telegraf.limitsMemory}}
{{- end}}
{{- end}}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if eq .Values.global.influxdbLocation "off-cluster" }}
        - name: "INFLUXDB_URLS_V2"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: url
        {{- else }}
        - name: "INFLUXDB_URLS_V2"
          value: "\"http://$(DRYCC_INFLUXDB_SERVICE_HOST):$(DRYCC_INFLUXDB_SERVICE_PORT_TRANSPORT)\""
        - name: "INFLUXDB_V2_INPUT_URLS"
          value: "\"http://$(DRYCC_INFLUXDB_SERVICE_HOST):$(DRYCC_INFLUXDB_SERVICE_PORT_TRANSPORT)/metrics\""
        - name: "ENABLE_INFLUXDB_V2_INPUT"
          value: "true"
        {{- end }}
        - name: "INFLUXDB_BUCKET"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: bucket
        - name: "INFLUXDB_ORG"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: org
        - name: "INFLUXDB_TOKEN"
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: token
        - name: "AGENT_QUIET"
          value: "true"
        - name: "AGENT_BUFFER_LIMIT"
          value: "100000"
{{- if eq .Values.global.redisLocation "on-cluster" }}
        - name: DRYCC_REDIS_ADDRS
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: addrs
        - name: DRYCC_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: password
{{- end }}
