{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: ClusterRole
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: drycc:drycc-monitor-telegraf
  labels:
    rbac.authorization.k8s.io/aggregate-view-telegraf-stats: "true"
    app: drycc-monitor-telegraf
    heritage: drycc
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "nodes/proxy", "nodes/stats"]
    verbs: ["get", "list", "watch"]
{{- end -}}
{{- end -}}
