{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: Role
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: drycc-monitor-telegraf
  labels:
    app: drycc-monitor-telegraf
    heritage: drycc
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
{{- end -}}
{{- end -}}
