{{- if eq .Values.global.grafana_location "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-monitor-grafana
  labels:
    heritage: drycc
    app: drycc-monitor-grafana
    router.drycc.cc/routable: "true"
  annotations:
    router.drycc.cc/domains: grafana
    router.drycc.cc/connectTimeout: "10"
    router.drycc.cc/tcpTimeout: "1200"
spec:
  ports:
  - port: 80
    name: ui
    targetPort: ui
  selector:
    app: drycc-monitor-grafana
{{- end }}
