grafana:
  org: "drycc"
  image_pull_policy: "Always"
  image_tag: "canary"
  image_registry: "docker.io"
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 5Gi
  # Any custom grafana environment variables
  # can be specified as key-value pairs under environment
  # this is usually a non required setting.
  environment:
    ALLOW_SIGN_UP: false
telegraf:
  org: "drycc"
  image_pull_policy: "Always"
  image_tag: "canary"
  image_registry: "docker.io"
  # limits_cpu: "100m"
  # limits_memory: "50Mi"

nsqd:
  replicas: 1
  tcp_port: 4150
  http_port: 4151

redis:
  replicas: 1
  port: "6379"

global:
  # Set the location of Workflow's influxdb cluster
  #
  # Valid values are:
  # - on-cluster: Run Influxdb within the Kubernetes cluster
  # - off-cluster: Influxdb is running outside of the cluster and credentials and connection information will be provided.
  influxdb_location: "on-cluster"
  # Set the location of Workflow's grafana instance
  #
  # Valid values are:
  # - on-cluster: Run Grafana within the Kubernetes cluster
  # - off-cluster: Grafana is running outside of the cluster
  grafana_location: "on-cluster"
  # Set the location of Workflow's redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in redis section)
  redis_location: "on-cluster"
  # Role-Based Access Control for Kubernetes >= 1.5
  use_rbac: false
  ingress_class: ""
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  cluster_domain: "cluster.local"
  # The public resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platform_domain: ""
  # Whether cert_manager is enabled to automatically generate drycc certificates
  cert_manager_enabled: "true"
