apiVersion: 1
datasources:
- name: Prometheus on Drycc
  type: prometheus
  access: proxy
  orgId: 1
  url: $DRYCC_VICTORIAMETRICS_URL
  isDefault: true
  jsonData:
    httpHeaderName1: X-Drycc-Service-Key
  secureJsonData:
    httpHeaderValue1: $DRYCC_SERVICE_KEY
  version: 1
  editable: false
