{{- if eq .Values.global.influxdb_location "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-monitor-influxui
  labels:
    heritage: drycc
    app: drycc-monitor-influxui
spec:
  ports:
  - port: 80
    name: admin
    targetPort: admin
  selector:
    app: drycc-monitor-influxdb
{{- end }}
